import os

# ── FILE 1: VideoRecorder component ──────────────────────────────────────────
recorder = (
    '"use client";\n'
    'import { useCallback, useEffect, useRef, useState } from "react";\n'
    'import { Video, Square, RotateCcw, Clock } from "lucide-react";\n\n'
    'interface Props {\n'
    '  onFile: (file: File) => void;\n'
    '  disabled?: boolean;\n'
    '}\n\n'
    'const DURATIONS = [30, 60, 90];\n\n'
    'export function VideoRecorder({ onFile, disabled }: Props) {\n'
    '  const [mode, setMode] = useState<"idle"|"preview"|"recording"|"done">("idle");\n'
    '  const [duration, setDuration] = useState(60);\n'
    '  const [timeLeft, setTimeLeft] = useState(60);\n'
    '  const [error, setError] = useState<string|null>(null);\n'
    '  const videoRef = useRef<HTMLVideoElement>(null);\n'
    '  const streamRef = useRef<MediaStream|null>(null);\n'
    '  const recorderRef = useRef<MediaRecorder|null>(null);\n'
    '  const chunksRef = useRef<Blob[]>([]);\n'
    '  const timerRef = useRef<NodeJS.Timeout|null>(null);\n\n'
    '  const startPreview = useCallback(async () => {\n'
    '    setError(null);\n'
    '    try {\n'
    '      const stream = await navigator.mediaDevices.getUserMedia({\n'
    '        video: { facingMode: "environment", width: { ideal: 1280 }, height: { ideal: 720 } },\n'
    '        audio: false,\n'
    '      });\n'
    '      streamRef.current = stream;\n'
    '      if (videoRef.current) {\n'
    '        videoRef.current.srcObject = stream;\n'
    '        videoRef.current.play();\n'
    '      }\n'
    '      setMode("preview");\n'
    '    } catch (e) {\n'
    '      setError("Camera access denied. Please allow camera access and try again.");\n'
    '    }\n'
    '  }, []);\n\n'
    '  const startRecording = useCallback(() => {\n'
    '    if (!streamRef.current) return;\n'
    '    chunksRef.current = [];\n'
    '    const mimeType = MediaRecorder.isTypeSupported("video/mp4") ? "video/mp4" : "video/webm";\n'
    '    const recorder = new MediaRecorder(streamRef.current, { mimeType });\n'
    '    recorder.ondataavailable = (e) => { if (e.data.size > 0) chunksRef.current.push(e.data); };\n'
    '    recorder.onstop = () => {\n'
    '      const blob = new Blob(chunksRef.current, { type: mimeType });\n'
    '      const ext = mimeType === "video/mp4" ? "mp4" : "webm";\n'
    '      const file = new File([blob], "pickleball-recording." + ext, { type: mimeType });\n'
    '      stopStream();\n'
    '      setMode("done");\n'
    '      onFile(file);\n'
    '    };\n'
    '    recorderRef.current = recorder;\n'
    '    recorder.start(1000);\n'
    '    setMode("recording");\n'
    '    setTimeLeft(duration);\n'
    '    timerRef.current = setInterval(() => {\n'
    '      setTimeLeft((t) => {\n'
    '        if (t <= 1) {\n'
    '          stopRecording();\n'
    '          return 0;\n'
    '        }\n'
    '        return t - 1;\n'
    '      });\n'
    '    }, 1000);\n'
    '  }, [duration, onFile]);\n\n'
    '  const stopRecording = useCallback(() => {\n'
    '    if (timerRef.current) clearInterval(timerRef.current);\n'
    '    if (recorderRef.current && recorderRef.current.state !== "inactive") {\n'
    '      recorderRef.current.stop();\n'
    '    }\n'
    '  }, []);\n\n'
    '  const stopStream = useCallback(() => {\n'
    '    if (timerRef.current) clearInterval(timerRef.current);\n'
    '    streamRef.current?.getTracks().forEach((t) => t.stop());\n'
    '    streamRef.current = null;\n'
    '  }, []);\n\n'
    '  const reset = useCallback(() => {\n'
    '    stopStream();\n'
    '    setMode("idle");\n'
    '    setError(null);\n'
    '  }, [stopStream]);\n\n'
    '  useEffect(() => () => stopStream(), [stopStream]);\n\n'
    '  if (mode === "idle") {\n'
    '    return (\n'
    '      <div className="rounded-2xl bg-green-600 p-6 text-white">\n'
    '        <div className="flex items-center gap-3 mb-4">\n'
    '          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-white/20">\n'
    '            <Video className="h-6 w-6 text-white" />\n'
    '          </div>\n'
    '          <div>\n'
    '            <p className="font-bold text-lg">Record at the Court</p>\n'
    '            <p className="text-sm text-green-100">Use your camera directly in the app</p>\n'
    '          </div>\n'
    '        </div>\n'
    '        <div className="mb-4">\n'
    '          <p className="text-sm text-green-100 mb-2">Recording duration:</p>\n'
    '          <div className="flex gap-2">\n'
    '            {[30, 60, 90].map((d) => (\n'
    '              <button key={d} onClick={() => setDuration(d)}\n'
    '                className={"flex-1 rounded-xl py-2 text-sm font-semibold transition-all " + (duration === d ? "bg-white text-green-700" : "bg-white/20 text-white hover:bg-white/30")}>\n'
    '                {d}s\n'
    '              </button>\n'
    '            ))}\n'
    '          </div>\n'
    '        </div>\n'
    '        {error && <p className="text-red-200 text-sm mb-3">{error}</p>}\n'
    '        <button onClick={startPreview} disabled={disabled}\n'
    '          className="w-full rounded-xl bg-white py-3 text-green-700 font-bold text-sm hover:bg-green-50 transition-colors disabled:opacity-50">\n'
    '          Open Camera\n'
    '        </button>\n'
    '      </div>\n'
    '    );\n'
    '  }\n\n'
    '  if (mode === "preview" || mode === "recording") {\n'
    '    return (\n'
    '      <div className="rounded-2xl overflow-hidden bg-black">\n'
    '        <div className="relative">\n'
    '          <video ref={videoRef} muted playsInline className="w-full" style={{maxHeight: "60vh", objectFit: "cover"}} />\n'
    '          {mode === "recording" && (\n'
    '            <div className="absolute top-3 right-3 flex items-center gap-2 bg-black/60 rounded-full px-3 py-1">\n'
    '              <div className="h-2 w-2 rounded-full bg-red-500 animate-pulse" />\n'
    '              <span className="text-white text-sm font-bold">{timeLeft}s</span>\n'
    '            </div>\n'
    '          )}\n'
    '        </div>\n'
    '        <div className="p-4 flex gap-3">\n'
    '          <button onClick={reset} className="flex-1 rounded-xl border border-white/30 py-3 text-white text-sm font-medium hover:bg-white/10">\n'
    '            Cancel\n'
    '          </button>\n'
    '          {mode === "preview" ? (\n'
    '            <button onClick={startRecording}\n'
    '              className="flex-2 flex-1 rounded-xl bg-red-500 py-3 text-white font-bold text-sm hover:bg-red-600 flex items-center justify-center gap-2">\n'
    '              <div className="h-3 w-3 rounded-full bg-white" />\n'
    '              Start Recording\n'
    '            </button>\n'
    '          ) : (\n'
    '            <button onClick={stopRecording}\n'
    '              className="flex-1 rounded-xl bg-red-500 py-3 text-white font-bold text-sm hover:bg-red-600 flex items-center justify-center gap-2">\n'
    '              <Square className="h-4 w-4 fill-white" />\n'
    '              Stop Early\n'
    '            </button>\n'
    '          )}\n'
    '        </div>\n'
    '      </div>\n'
    '    );\n'
    '  }\n\n'
    '  return null;\n'
    '}\n'
)

# ── FILE 2: Updated home page ─────────────────────────────────────────────────
homepage = (
    '// @ts-nocheck\n'
    '"use client";\n'
    'import { useRouter } from "next/navigation";\n'
    'import { useEffect, useState } from "react";\n'
    'import { VideoDropzone } from "@/components/upload/VideoDropzone";\n'
    'import { VideoRecorder } from "@/components/upload/VideoRecorder";\n'
    'import { UploadProgress } from "@/components/upload/UploadProgress";\n'
    'import { useUpload } from "@/hooks/useUpload";\n\n'
    'export default function HomePage() {\n'
    '  const { state, upload, reset } = useUpload();\n'
    '  const router = useRouter();\n'
    '  const [mode, setMode] = useState<"choose"|"record"|"upload">("choose");\n\n'
    '  useEffect(() => {\n'
    '    if (state.phase === "done") {\n'
    '      router.push("/analysis/" + ("analysisId" in state ? state.analysisId : ""));\n'
    '    }\n'
    '  }, [state, router]);\n\n'
    '  const handleFile = (file: File) => upload(file, "all");\n\n'
    '  const isActive = state.phase !== "idle" && state.phase !== "error";\n\n'
    '  return (\n'
    '    <div className="space-y-6">\n'
    '      <div>\n'
    '        <h1 className="text-2xl font-bold text-gray-900">Analyze Your Game</h1>\n'
    '        <p className="mt-1 text-gray-500">Record or upload a pickleball video to get AI-powered ratings and pro tips for all 4 players.</p>\n'
    '      </div>\n\n'
    '      {!isActive && mode === "choose" && (\n'
    '        <div className="space-y-3">\n'
    '          <button onClick={() => setMode("record")}\n'
    '            className="w-full rounded-2xl bg-green-600 p-5 text-left hover:bg-green-700 transition-colors">\n'
    '            <p className="text-white font-bold text-lg">Record at the Court</p>\n'
    '            <p className="text-green-100 text-sm mt-0.5">Use your camera directly in the app</p>\n'
    '          </button>\n'
    '          <button onClick={() => setMode("upload")}\n'
    '            className="w-full rounded-2xl border-2 border-dashed border-gray-300 p-5 text-left hover:border-green-400 hover:bg-green-50/30 transition-colors">\n'
    '            <p className="text-gray-800 font-bold text-lg">Upload Existing Video</p>\n'
    '            <p className="text-gray-500 text-sm mt-0.5">MP4 or WebM, max 200MB</p>\n'
    '          </button>\n'
    '        </div>\n'
    '      )}\n\n'
    '      {!isActive && mode === "record" && (\n'
    '        <div className="space-y-3">\n'
    '          <button onClick={() => setMode("choose")} className="text-sm text-gray-500 hover:text-gray-700">\n'
    '            Back\n'
    '          </button>\n'
    '          <VideoRecorder onFile={handleFile} disabled={isActive} />\n'
    '        </div>\n'
    '      )}\n\n'
    '      {!isActive && mode === "upload" && (\n'
    '        <div className="space-y-3">\n'
    '          <button onClick={() => setMode("choose")} className="text-sm text-gray-500 hover:text-gray-700">\n'
    '            Back\n'
    '          </button>\n'
    '          <VideoDropzone onFile={handleFile} disabled={isActive} />\n'
    '        </div>\n'
    '      )}\n\n'
    '      {(state.phase === "uploading" || state.phase === "processing" || state.phase === "done") && (\n'
    '        <UploadProgress phase={state.phase} progress={"progress" in state ? state.progress : undefined} />\n'
    '      )}\n\n'
    '      {state.phase === "error" && (\n'
    '        <>\n'
    '          <UploadProgress phase="error" message={state.message} />\n'
    '          <button onClick={() => { reset(); setMode("choose"); }}\n'
    '            className="w-full rounded-lg border border-gray-300 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50">\n'
    '            Try again\n'
    '          </button>\n'
    '        </>\n'
    '      )}\n'
    '    </div>\n'
    '  );\n'
    '}\n'
)

files = {
    r"C:\Users\blair\Documents\pickleball-analyzer\apps\web\components\upload\VideoRecorder.tsx": recorder,
    r"C:\Users\blair\Documents\pickleball-analyzer\apps\web\app\(dashboard)\page.tsx": homepage,
}

for path, content in files.items():
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("Written:", path)

print("ALL DONE")