path = r"C:\Users\blair\Documents\pickleball-analyzer\apps\web\app\api\videos\process\route.ts"
content = (
    'import { NextResponse } from "next/server";\n'
    'import { createClient, createServiceClient } from "@/lib/supabase/server";\n\n'
    'export const maxDuration = 60;\n\n'
    'export async function POST(request: Request) {\n'
    '  const supabase = await createClient();\n'
    '  const { data: { user } } = await supabase.auth.getUser();\n'
    '  if (!user) {\n'
    '    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });\n'
    '  }\n\n'
    '  const { analysisId, videoPath } = await request.json();\n'
    '  console.log("[process] Starting for analysisId:", analysisId);\n\n'
    '  const serviceClient = await createServiceClient();\n\n'
    '  const { data: analysis } = await serviceClient\n'
    '    .from("analyses")\n'
    '    .select("id, user_id")\n'
    '    .eq("id", analysisId)\n'
    '    .eq("user_id", user.id)\n'
    '    .single();\n\n'
    '  if (!analysis) {\n'
    '    console.log("[process] Analysis not found:", analysisId);\n'
    '    return NextResponse.json({ error: "Analysis not found" }, { status: 404 });\n'
    '  }\n\n'
    '  await serviceClient\n'
    '    .from("analyses")\n'
    '    .update({ status: "processing", processing_started_at: new Date().toISOString() })\n'
    '    .eq("id", analysisId);\n\n'
    '  const processorUrl = process.env.VIDEO_PROCESSOR_URL ?? "http://localhost:8000";\n'
    '  const secret = process.env.VIDEO_PROCESSOR_SECRET ?? "";\n'
    '  console.log("[process] Calling Render at:", processorUrl);\n\n'
    '  try {\n'
    '    const renderRes = await fetch(processorUrl + "/process", {\n'
    '      method: "POST",\n'
    '      headers: {\n'
    '        "Content-Type": "application/json",\n'
    '        "X-Secret": secret,\n'
    '      },\n'
    '      body: JSON.stringify({\n'
    '        analysis_id: analysisId,\n'
    '        video_storage_path: videoPath,\n'
    '        user_id: user.id,\n'
    '      }),\n'
    '      signal: AbortSignal.timeout(8000),\n'
    '    });\n'
    '    console.log("[process] Render responded:", renderRes.status);\n'
    '  } catch (err) {\n'
    '    console.error("[process] Render call failed:", err);\n'
    '    await serviceClient\n'
    '      .from("analyses")\n'
    '      .update({ status: "failed", error_message: "Processor unreachable - please try again" })\n'
    '      .eq("id", analysisId);\n'
    '  }\n\n'
    '  return NextResponse.json({ analysisId, status: "processing" });\n'
    '}\n'
)
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Done!")