path = r"C:\Users\blair\Documents\pickleball-analyzer\services\video-processor\app\main.py"
content = (
    'import asyncio\n'
    'import traceback\n'
    'from fastapi import FastAPI\n'
    'from fastapi.middleware.cors import CORSMiddleware\n'
    'from app.routers import process, health\n'
    'from app.pipeline.runner import run_pipeline\n'
    'from app.db.supabase_client import update_analysis\n'
    'from app.config import settings\n'
    'import os\n\n'
    'app = FastAPI(title="Pickleball Video Processor", version="1.0.0")\n'
    'app.add_middleware(\n'
    '    CORSMiddleware,\n'
    '    allow_origins=["*"],\n'
    '    allow_methods=["POST", "GET"],\n'
    '    allow_headers=["Authorization", "Content-Type"],\n'
    ')\n'
    'app.include_router(health.router)\n'
    'app.include_router(process.router)\n\n'
    'currently_processing = set()\n\n'
    'async def poll_pending_analyses():\n'
    '    """Poll Supabase every 30 seconds for pending analyses and process them."""\n'
    '    from supabase import create_client\n'
    '    supabase_url = os.environ.get("SUPABASE_URL", "")\n'
    '    supabase_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")\n'
    '    if not supabase_url or not supabase_key:\n'
    '        print("[poller] Missing Supabase credentials - polling disabled", flush=True)\n'
    '        return\n'
    '    client = create_client(supabase_url, supabase_key)\n'
    '    print("[poller] Started - checking every 30 seconds for pending analyses", flush=True)\n'
    '    while True:\n'
    '        try:\n'
    '            res = client.from_("analyses")\\\n'
    '                .select("id, video_path, user_id")\\\n'
    '                .eq("status", "pending")\\\n'
    '                .order("created_at", desc=False)\\\n'
    '                .limit(3)\\\n'
    '                .execute()\n'
    '            pending = res.data or []\n'
    '            if pending:\n'
    '                print(f"[poller] Found {len(pending)} pending analyses", flush=True)\n'
    '            for item in pending:\n'
    '                aid = item["id"]\n'
    '                if aid in currently_processing:\n'
    '                    continue\n'
    '                currently_processing.add(aid)\n'
    '                print(f"[poller] Triggering pipeline for {aid}", flush=True)\n'
    '                loop = asyncio.get_event_loop()\n'
    '                loop.run_in_executor(None, run_pipeline_safe, aid, item["video_path"], item["user_id"])\n'
    '        except Exception as e:\n'
    '            print(f"[poller] Error: {e}", flush=True)\n'
    '        await asyncio.sleep(30)\n\n'
    'def run_pipeline_safe(analysis_id, video_path, user_id):\n'
    '    try:\n'
    '        print(f"[poller] Running pipeline for {analysis_id}", flush=True)\n'
    '        run_pipeline(analysis_id, video_path, user_id)\n'
    '        print(f"[poller] Pipeline complete for {analysis_id}", flush=True)\n'
    '    except Exception as e:\n'
    '        print(f"[poller] Pipeline failed for {analysis_id}: {e}", flush=True)\n'
    '        print(traceback.format_exc(), flush=True)\n'
    '    finally:\n'
    '        currently_processing.discard(analysis_id)\n\n'
    '@app.on_event("startup")\n'
    'async def startup_event():\n'
    '    asyncio.create_task(poll_pending_analyses())\n'
    '    print("[startup] Polling loop started", flush=True)\n'
)
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Done!")