path = r"C:\Users\blair\Documents\pickleball-analyzer\apps\web\app\api\videos\upload-url\route.ts"
content = (
    'import { NextResponse } from "next/server";\n'
    'import { createClient, createServiceClient } from "@/lib/supabase/server";\n'
    'const MAX_SIZE_BYTES = 200 * 1024 * 1024;\n\n'
    'async function triggerProcessingWithDelay(processorUrl: string, secret: string, analysisId: string, videoPath: string, userId: string, serviceClient: any) {\n'
    '  // Wait 30 seconds for the upload to complete before triggering\n'
    '  await new Promise(r => setTimeout(r, 30000));\n'
    '  console.log("[upload-url] Triggering Render for:", analysisId);\n'
    '  try {\n'
    '    const res = await fetch(processorUrl + "/process", {\n'
    '      method: "POST",\n'
    '      headers: { "Content-Type": "application/json", "X-Secret": secret },\n'
    '      body: JSON.stringify({ analysis_id: analysisId, video_storage_path: videoPath, user_id: userId }),\n'
    '      signal: AbortSignal.timeout(10000),\n'
    '    });\n'
    '    console.log("[upload-url] Render responded:", res.status);\n'
    '    await serviceClient.from("analyses").update({ status: "processing", processing_started_at: new Date().toISOString() }).eq("id", analysisId);\n'
    '  } catch (err) {\n'
    '    console.error("[upload-url] Render trigger failed:", err);\n'
    '    await serviceClient.from("analyses").update({ status: "failed", error_message: "Processor unreachable" }).eq("id", analysisId);\n'
    '  }\n'
    '}\n\n'
    'export const maxDuration = 60;\n\n'
    'export async function POST(request: Request) {\n'
    '  const supabase = await createClient();\n'
    '  const { data: { user } } = await supabase.auth.getUser();\n'
    '  if (!user) {\n'
    '    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });\n'
    '  }\n'
    '  const { fileName, fileSize, contentType } = await request.json();\n'
    '  if (fileSize > MAX_SIZE_BYTES) {\n'
    '    return NextResponse.json({ error: "File too large. Maximum size is 200MB." }, { status: 400 });\n'
    '  }\n'
    '  const allowedTypes = ["video/", "image/jpeg", "image/png", "application/octet-stream"];\n'
    '  const isAllowed = allowedTypes.some(t => contentType.startsWith(t)) || !contentType;\n'
    '  if (!isAllowed) {\n'
    '    return NextResponse.json({ error: "Only video files are allowed." }, { status: 400 });\n'
    '  }\n'
    '  const serviceClient = await createServiceClient();\n'
    '  const { data: analysis, error: dbError } = await serviceClient\n'
    '    .from("analyses")\n'
    '    .insert({ user_id: user.id, video_path: "", video_size_bytes: fileSize, status: "pending" })\n'
    '    .select("id")\n'
    '    .single();\n'
    '  if (dbError || !analysis) {\n'
    '    return NextResponse.json({ error: "Failed to create analysis record" }, { status: 500 });\n'
    '  }\n'
    '  const videoPath = user.id + "/" + analysis.id + "/" + fileName;\n'
    '  await serviceClient.from("analyses").update({ video_path: videoPath }).eq("id", analysis.id);\n'
    '  const { data: signedData, error: signedError } = await serviceClient.storage\n'
    '    .from("videos")\n'
    '    .createSignedUploadUrl(videoPath);\n'
    '  if (signedError || !signedData) {\n'
    '    return NextResponse.json({ error: "Failed to create upload URL" }, { status: 500 });\n'
    '  }\n'
    '  const processorUrl = process.env.VIDEO_PROCESSOR_URL ?? "http://localhost:8000";\n'
    '  const secret = process.env.VIDEO_PROCESSOR_SECRET ?? "";\n'
    '  // Fire delayed trigger - no await, runs in background\n'
    '  triggerProcessingWithDelay(processorUrl, secret, analysis.id, videoPath, user.id, serviceClient);\n'
    '  return NextResponse.json({ uploadUrl: signedData.signedUrl, analysisId: analysis.id, videoPath });\n'
    '}\n'
)
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Done!")