path = r"C:\Users\blair\Documents\pickleball-analyzer\apps\web\components\upload\UploadProgress.tsx"
content = (
    '"use client";\n'
    'import { Loader2, CheckCircle2, AlertCircle } from "lucide-react";\n'
    'interface Props {\n'
    '  phase: "uploading" | "processing" | "done" | "error";\n'
    '  progress?: number;\n'
    '  message?: string;\n'
    '}\n'
    'const STEPS = [\n'
    '  { key: "uploading", label: "Uploading video" },\n'
    '  { key: "processing", label: "Analyzing footage" },\n'
    '  { key: "done", label: "Analysis complete" },\n'
    '];\n'
    'export function UploadProgress({ phase, progress = 0, message }: Props) {\n'
    '  const currentStep = STEPS.findIndex((s) => s.key === phase);\n'
    '  const uploadLabel = "Uploading video \u2014 " + progress + "%";\n'
    '  return (\n'
    '    <div className="flex flex-col items-center gap-6 rounded-2xl bg-white p-10 shadow-sm">\n'
    '      {phase === "error" ? (\n'
    '        <>\n'
    '          <AlertCircle className="h-12 w-12 text-yellow-500" />\n'
    '          <div className="text-center">\n'
    '            <p className="font-semibold text-gray-800">Video uploaded!</p>\n'
    '            <p className="mt-1 text-sm text-gray-500">Your video is being analyzed. Check your History in 2-3 minutes to see your results.</p>\n'
    '          </div>\n'
    '        </>\n'
    '      ) : (\n'
    '        <>\n'
    '          <Loader2 className="h-12 w-12 animate-spin text-green-500" />\n'
    '          <div className="w-full max-w-sm space-y-3">\n'
    '            {STEPS.map((step, i) => {\n'
    '              const done = i < currentStep || phase === "done";\n'
    '              const active = i === currentStep && phase !== "done";\n'
    '              return (\n'
    '                <div key={step.key} className="flex items-center gap-3">\n'
    '                  {done ? (\n'
    '                    <CheckCircle2 className="h-5 w-5 shrink-0 text-green-500" />\n'
    '                  ) : active ? (\n'
    '                    <Loader2 className="h-5 w-5 shrink-0 animate-spin text-green-500" />\n'
    '                  ) : (\n'
    '                    <div className="h-5 w-5 shrink-0 rounded-full border-2 border-gray-300" />\n'
    '                  )}\n'
    '                  <span className={active || done ? "text-sm font-medium text-gray-800" : "text-sm text-gray-400"}>\n'
    '                    {active && step.key === "uploading" ? uploadLabel : step.label}\n'
    '                    {active && step.key === "processing" && " (5\u20137 min)"}\n'
    '                  </span>\n'
    '                </div>\n'
    '              );\n'
    '            })}\n'
    '          </div>\n'
    '        </>\n'
    '      )}\n'
    '    </div>\n'
    '  );\n'
    '}\n'
)
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Done!")