path = r"C:\Users\blair\Documents\pickleball-analyzer\apps\web\hooks\useUpload.ts"
content = content = (
    '// @ts-nocheck\n'
    'import { useState, useCallback } from "react";\n'
    'export function useUpload() {\n'
    '  const [state, setState] = useState({ phase: "idle" });\n'
    '  const upload = useCallback(async (file, playerPosition) => {\n'
    '    setState({ phase: "uploading", progress: 0 });\n'
    '    try {\n'
    '      const res = await fetch("/api/videos/upload-url", {\n'
    '        method: "POST",\n'
    '        headers: { "Content-Type": "application/json" },\n'
    '        body: JSON.stringify({\n'
    '          fileName: file.name,\n'
    '          fileSize: file.size,\n'
    '          contentType: file.type || "video/quicktime",\n'
    '        }),\n'
    '      });\n'
    '      if (!res.ok) {\n'
    '        const err = await res.json();\n'
    '        throw new Error(err.error ?? "Failed to prepare upload");\n'
    '      }\n'
    '      const { uploadUrl, analysisId, videoPath } = await res.json();\n'
    '      await new Promise((resolve, reject) => {\n'
    '        const xhr = new XMLHttpRequest();\n'
    '        xhr.timeout = 300000;\n'
    '        xhr.upload.addEventListener("progress", (e) => {\n'
    '          if (e.lengthComputable) {\n'
    '            setState({ phase: "uploading", progress: Math.round((e.loaded / e.total) * 100) });\n'
    '          }\n'
    '        });\n'
    '        xhr.addEventListener("load", () => {\n'
    '          if (xhr.status >= 200 && xhr.status < 300) resolve();\n'
    '          else reject(new Error("Upload failed: " + xhr.status));\n'
    '        });\n'
    '        xhr.addEventListener("error", () => reject(new Error("Network error during upload")));\n'
    '        xhr.addEventListener("timeout", () => reject(new Error("Upload timed out - try a shorter video")));\n'
    '        xhr.open("PUT", uploadUrl);\n'
    '        xhr.setRequestHeader("Content-Type", file.type || "video/quicktime");\n'
    '        xhr.send(file);\n'
    '      });\n'
    '      // Fire and forget - poller will pick it up\n'
    '      fetch("/api/videos/process", {\n'
    '        method: "POST",\n'
    '        headers: { "Content-Type": "application/json" },\n'
    '        body: JSON.stringify({ analysisId, videoPath, playerPosition }),\n'
    '      }).catch((e) => console.error("Process fetch error:", e));\n'
    '      // Redirect to analysis page immediately\n'
    '      setState({ phase: "done", analysisId });\n'
    '    } catch (err) {\n'
    '      setState({\n'
    '        phase: "error",\n'
    '        message: err instanceof Error ? err.message : "Upload failed",\n'
    '      });\n'
    '    }\n'
    '  }, []);\n'
    '  const reset = useCallback(() => setState({ phase: "idle" }), []);\n'
    '  return { state, upload, reset };\n'
    '}\n'
)
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Done!")